#!/usr/bin/env python3
"""Materialize config/.env.compose from environment variables (deploy / CI).

Never prints secret values. Used by GitHub Actions deploy workflow skeleton.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Keys written to config/.env.compose (must match config/.env.compose.example)
_ENV_KEYS = (
    "POSTGRES_USER",
    "POSTGRES_PASSWORD",
    "POSTGRES_DB",
    "DB_USER",
    "DB_PASSWORD",
    "DB_HOST",
    "DB_PORT",
    "DB_NAME",
    "DATABASE_URL",
    "GRAFANA_ADMIN_PASSWORD",
    "N8N_BASIC_AUTH_USER",
    "N8N_BASIC_AUTH_PASSWORD",
    "N8N_ENCRYPTION_KEY",
    "JWT_SECRET",
    "ENCRYPT_KEY",
    "SECRET_KEY",
    "API_KEY",
)


def _project_root() -> Path:
    return Path(__file__).resolve().parents[2]


def write_compose_env(
    target: Path,
    *,
    require_all: bool,
    allow_missing: bool,
) -> int:
    lines: list[str] = [
        "# Generated by scripts/deploy/write_compose_env.py - do not commit.",
        "",
    ]
    missing: list[str] = []

    for key in _ENV_KEYS:
        value = os.getenv(key)
        if value is None or value == "":
            if require_all:
                missing.append(key)
            continue
        lines.append(f"{key}={value}")

    if missing and not allow_missing:
        print(
            "[FAIL] Missing required environment variables: "
            + ", ".join(missing),
            file=sys.stderr,
        )
        return 1

    if "DATABASE_URL" not in os.environ or not os.getenv("DATABASE_URL"):
        db_user = os.getenv("DB_USER") or os.getenv("POSTGRES_USER") or "postgres"
        db_password = os.getenv("DB_PASSWORD") or os.getenv("POSTGRES_PASSWORD") or ""
        db_host = os.getenv("DB_HOST", "postgres")
        db_port = os.getenv("DB_PORT", "5432")
        db_name = os.getenv("DB_NAME") or os.getenv("POSTGRES_DB") or "vita_db"
        if db_password and not any(line.startswith("DATABASE_URL=") for line in lines):
            lines.append(
                "DATABASE_URL="
                f"postgresql+psycopg2://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}"
            )

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[OK] Wrote compose env file: {target} ({len(lines) - 2} keys)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Write config/.env.compose from env")
    parser.add_argument(
        "--output",
        type=Path,
        default=_project_root() / "config" / ".env.compose",
        help="Output path (default: config/.env.compose)",
    )
    parser.add_argument(
        "--from-env",
        action="store_true",
        help="Read all keys from current process environment",
    )
    parser.add_argument(
        "--require-all",
        action="store_true",
        help="Fail if any key in the template is missing from environment",
    )
    parser.add_argument(
        "--allow-missing",
        action="store_true",
        help="Write partial file (staging bootstrap)",
    )
    args = parser.parse_args()

    if not args.from_env:
        print("[FAIL] Currently only --from-env is supported", file=sys.stderr)
        return 2

    return write_compose_env(
        args.output,
        require_all=args.require_all,
        allow_missing=args.allow_missing,
    )


if __name__ == "__main__":
    raise SystemExit(main())
