#!/usr/bin/env python3
"""Render Grafana clinical alert contact point from environment (P5-1).

Uses GRAFANA_CLINICAL_ALERT_WEBHOOK_URL, falling back to ESCALATION_WEBHOOK_URL.
When neither is set, keeps a no-op URL (alerts visible in Grafana UI only).

Usage:
    python scripts/observability/render_grafana_alert_contact.py
    python scripts/observability/render_grafana_alert_contact.py --check-only
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

_NOOP_URL = "http://127.0.0.1:65534/noop"
_OUTPUT_REL = Path("grafana/provisioning/alerting/contactpoints.yaml")


def _project_root() -> Path:
    return Path(__file__).resolve().parents[2]


def resolve_clinical_webhook_url() -> tuple[str, str]:
    """Return (url, source_label)."""
    for key in ("GRAFANA_CLINICAL_ALERT_WEBHOOK_URL", "ESCALATION_WEBHOOK_URL"):
        value = os.getenv(key, "").strip()
        if value:
            return value, key
    return _NOOP_URL, "noop (Grafana UI only)"


def render_contactpoints_yaml(webhook_url: str) -> str:
    return f"""# Generated by scripts/observability/render_grafana_alert_contact.py — do not edit.
# Clinical alert routing (P5-1).
apiVersion: 1

contactPoints:
  - orgId: 1
    name: vita-clinical-webhook
    receivers:
      - uid: vita-clinical-webhook
        type: webhook
        settings:
          url: {webhook_url}
          httpMethod: POST
        disableResolveMessage: false
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render Grafana clinical alert contact point")
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="Print resolved URL source without writing file",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=_project_root() / _OUTPUT_REL,
        help="Output contactpoints.yaml path",
    )
    args = parser.parse_args(argv)

    url, source = resolve_clinical_webhook_url()
    if args.check_only:
        print(f"[INFO] clinical alert webhook source: {source}")
        if url == _NOOP_URL:
            print("[WARN] No webhook configured; alerts will not leave Grafana")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_contactpoints_yaml(url), encoding="utf-8")
    print(f"[OK] Wrote {args.output} (source: {source})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
